### ISSUE TITLE
Add `RefScope` as argument to `git::repo::revision_branches`

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-git#13]
Currently we retrieve all branch references, iterate over all of them and check if the passed Oid is contained in them.
https://github.com/radicle-dev/radicle-git/blob/58d69ebf7f441cfde043593fc7efbc8912033759/radicle-surf/src/vcs/git/repo.rs#L259

I think we could optimize this, by adding a `RefScope` argument e.g.
`fn revision_branches(&self, oid: &Oid, scope: RefScope) -> Result<Vec<Branch>, Error>`

This would allow us to initially create a Vector and retrieve only the local, or only remote or both if needed, and then check over that vector if the Oid is contained in any branch.

**Comment by FintanH** [comment]
So with the unification of all git things into this repo, I think the best route is actually doing away with these custom types and using the `git-ref-format` package. This operation would then be defined in terms of a `PatternStr`, something like:

```rust
pub fn revision_branches(&self, oid: &Oid, pat: Option<PatternStr>) -> Result<Vec<RefString>, Error> {
   let refs = self.references(pat)?;
   Ok(refs.filter_map(|r| if contains(r, oid) then Some(r) else None))
}
```

If waiting for this refactor is a problem though, then an `Option<RefScope>` works too :)

**Comment by sebastinez** [comment]
Ok nice, yeah it's not something that cannot wait, but will eventually provide a PR just to make it nicer for the `http-api` in the meanwhile 😁

**Comment by FintanH** [comment]
> Ok nice, yeah it's not something that cannot wait, but will eventually provide a PR just to make it nicer for the `http-api` in the meanwhile grin

A double negative :eyes: So it _can_ wait? :joy:

**Comment by FintanH** [comment]
Cool! Well if you'd like to help out on the `git-ref-format` migration, always happy to look at PRs or issues :)

**Comment by keepsimple1** [comment]
@sebastinez I would love to get your comments, especially regarding `revision_branches` changes in the attached PR #44 .

**Comment by sebastinez** [comment]
> @sebastinez I would love to get your comments, especially regarding `revision_branches` changes in the attached PR #44 .

Hey @keepsimple1 honestly not really able to give you a review on the whole PR, but the `revision_branches` function looks great, and seems to fix this issue
