### ISSUE TITLE
`diff::Moved` might require object IDs and file modes

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/radicle-git#140]
A recent [Radicle Patch](https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/commits/c55badf0b8bee38e425d297decbd3560fad3c5e7) for heartwood indicates git files which are moved can have oids and file modes.

```
git show c55badf0b8bee38e425d297decbd3560fad3c5e7 | grep -A5 b/radicle/src/node/tracking/config.rs
diff --git a/radicle-node/src/service/tracking.rs b/radicle/src/node/tracking/config.rs
similarity index 96%
rename from radicle-node/src/service/tracking.rs
rename to radicle/src/node/tracking/config.rs
index cbc843c8..3f69208f 100644
```

However `diff::Moved` uses `PathBuf` as fields, where DiffFile might be better:

```
pub struct Moved {
    /// The old path to this file, relative to the repository root.
    pub old_path: PathBuf,
    /// The new path to this file, relative to the repository root.
    pub new_path: PathBuf,
    pub diff: DiffContent,
}
```

**Comment by FintanH** [comment]
Good catch. I also realised we're not serializing the diff content for compatibility reasons. I'm thinking we could serialize them only if there is a move with a change.
