### ISSUE TITLE
Reminder to re-enable diff tests once upgrading to libgit2 v1.8

### ISSUE THREAD

**Issue by xphoniex** [radicle-dev/radicle-git#149]
[Two tests](https://github.com/radicle-dev/radicle-git/blob/main/radicle-surf/t/src/diff.rs#L657-L697) were commented out given the underlying bug in libgit2, which has just been [fixed](https://github.com/libgit2/libgit2/pull/6240), scheduled to release in v1.8.

Reminder to re-enable them once you upgrade to the coinciding git2 crate. Cheers!

**Comment by FintanH** [comment]
Fixed in https://github.com/radicle-dev/radicle-git/commit/224ad083669dcf4ab2f19813c79340b6ea58ca4c
