### ISSUE TITLE
gitd port

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-git#2]
I'm currently scoping out the port of `gitd` and making it generic over the more `librad`-specific parts.

The main loop uses `PeerId` to create/load a `thrussh::KeyPair`. I've made the `thrussh` code generic over the key, so we should be able to use our own key types for this instead. However, since this is generic git code, I think our first need is some sort of `KeyStore` trait that knows how to load a key and this can be passed on to `thrussh`.

The next thing to look at is `hooks.rs`, which currently uses `librad` to access storage for updating signed refs and talking to seeds in `pre_` and `post_` upload functions, relied on by `git_subprocess`. My thinking here is that we make these two traits `PreUpload` and `PostUpload`. They are unopinionated, `async` functions and the end-consumer can do what they like here, e.g. update signed refs, do nothing, talk to external seeds.

I think that covers all the bases, but always the chance I could be missing something :)

Any thoughts @alexjg, if you have the time?

**Comment by FintanH** [comment]
Two parts that I did miss:
1) The ssh path is using `Urn` which depending on the way we go for project identifiers may need to be changed. I could either leave it as-is for now using the `git_types:Urn` instead, or I could use something like `std::path::Component`.
2) The socket activation code that lives in `lnk-clib` which is used by `lnk-gitd` and `linkd`. I could just copy code over from and make it part of the gitd code, but that could end up in duplication if we're keeping `linkd`. I'm wondering what's the plan there, @cloudhead.

**Comment by alexjg** [comment]
I think it's worth introducing a trait to cover the way the `git` subprocess is run. In general it seems like we will want to do ref-rewriting to massage the monorepo layout into something which vanilla git clients can interact with. However, there may be two separate ways this is achieved:

1. By providing wrapped versions of `git-upload-pack` and `git-receive-pack` etc which the `gitd` can just call out to directly. In that case the current implementation (which just uses whatever `git-upload-pack` is on the PATH) will work fine.
2. Wrapping calls to the subprocess _within_ the `gitd`. This is the approach I've been working on in `gitd`.

The first approach is probably better for seeds, where `git-upload-pack` may be required for non `gitd` related reasons. But the latter approach is better on your personal machine, where you don't want to have to deploy special versions of `git-*`.

Therefore it seems like you probably want a trait which handles the handling of the bytes which are passed through to the subprocess and returned from it.

**Comment by alexjg** [comment]
By per-directory do you mean a uniform namespace layout? I.e. `refs/namespaces/<project ID>/refs/namespaces/<peer ID>`?

**Comment by alexjg** [comment]
Erm, no wait I see what you mean, you mean the sans monorepo approach? Yeah iN that case it's probably unnecessary to do ref-rewriting and I think the extension points you've outlined would be sufficient.

**Comment by cloudhead** [comment]
Since socket-activation is kind of os-specific, while at the same time meant to be used on end-user machines, I wouldn't priortize it.

At the moment, we're looking at mainly two setups:
1. user runs peer to peer node locally, they push via `rad push`, seed fetches from user directly (implies some NAT traversal)
2. user doesn't run peer to peer node, they push to seed via a git bridge/proxy running on the seed (this would be gitd)

Both of these setutps *could* also use a *local* gitd, allowing users to use git directly without `rad`, which is what gitd was already designed for. As long as it consumes close to 0% cpu and memory while idle, I don't see an issue with having it running in the background.

**Comment by FintanH** [comment]
This isn't needed after going down the route of namespaces and a new rad-remote-helper
