### ISSUE TITLE
`git-url` improvements

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-git#20]
I've been using `git-url` quite a bit, instead of the `url` crate, as it's a bit easier to use for our purposes, but there's a few things that could be improved:

* `FromStr` instance would be nice
* Some constructors eg. `Url::file(path: Path)`, `Url::ssh(impl Into<net::SocketAddr>)` etc.
* The `path` field must have a `/` prefixed otherwise it gets appended to the host without a `/`. It would be nice if it did this automatically.
* Some interop with `Path` for the `path` component (could just be the `Url::file` constructor), which is useful with the `File` scheme. Eg. right now I have to construct URLs like this:

```rust
Url {
 ...
 path: file
         .path()
         .join(proj_id.to_string())
         .to_string_lossy()
         .into_owned()
         .into(),
}

**Comment by FintanH** [comment]
> I've been using `git-url` quite a bit

As in this [`git-url`](https://docs.rs/git-url/0.9.0/git_url/)?

**Comment by cloudhead** [comment]
Yes, I just realized it's not our crate :D 

I think we were using it in link and I started using it as well :shrug:

**Comment by FintanH** [comment]
Seems like it doesn't depend on a lot of other gitoxide so it's _probably_ safe to use :innocent:

**Comment by cloudhead** [comment]
Should we be contributing changes there then? Or should we fork it into radicle-git?

**Comment by FintanH** [comment]
> Should we be contributing changes there then? Or should we fork it into radicle-git?

Let's contribute there :) If we _need_ to we can fork here :v:
