### ISSUE TITLE
Should we have `test_` prefix for test files?

### ISSUE THREAD

**Issue by keepsimple1** [radicle-dev/radicle-git#25]
In my opinion, `test_` lets the reader know immediately that the file is a test code. Overall, the benefits outweigh the slightly longer prefix. However, there are other opinions. This issue is to track the discussions about this topic.

        I'd prefer without the `test_` prefix here. We know they're tests ;)

_Originally posted by @FintanH in https://github.com/radicle-dev/radicle-git/pull/23#discussion_r982173902_

**Comment by FintanH** [comment]
@FintanH also said:

https://github.com/radicle-dev/radicle-git/pull/23#discussion_r983194685
