### ISSUE TITLE
radicle-surf: refactoring `Directory` ideas

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-git#49]
I was exploring using [`git2::Tree`](https://docs.rs/git2/0.15.0/git2/struct.Tree.html#) as a way of defining a `Directory`. I was wondering if this would be a good model because `Tree` already has a couple of nice functions:
* [`get_name`](https://docs.rs/git2/0.15.0/git2/struct.Tree.html#method.get_name) -- look at the name of this entry, if it exists. Which can be used to either get a file or go to the next level of the directory.
* [`get_path`](https://docs.rs/git2/0.15.0/git2/struct.Tree.html#method.get_path) -- gets an entry based on the path, relative to where you are in the tree, i.e. you can ask for something a few levels down.

The annoying thing about this though is that [`git2::TreeEntry`](https://docs.rs/git2/0.15.0/git2/struct.TreeEntry.html) has a method [`to_object`](https://docs.rs/git2/0.15.0/git2/struct.TreeEntry.html#method.to_object) which requires a `git2::Repository`. That would mean that a `Directory` would need to carry around a reference to the repository. It's not the worst thing in the world, but I'd rather not have some `struct` carrying around a handle to the repository.

At the least, I'd like to remove the `file_system::path` stuff from `radicle-surf` and use the `std::path::Path` instead.

**Comment by keepsimple1** [comment]
I don't think we need to build directly on top of `git2::Tree`, but I like the idea of having `object_id` (type `Oid`) as part of `DirectoryContent` type.  

How about we obtain the `object_id` during `Respository:;snapshot()`? (The actual work is in [`directory_of_commit`](https://github.com/radicle-dev/radicle-git/blob/55668e6e0f07abfb3a2bdc9ac8699a656d455ffd/radicle-surf/src/vcs/git/repo.rs#L433)).

With the `object_id`, the user can obtain further info about a `Directory` or `File` easily during traversal or listing.

**Comment by FintanH** [comment]
> I'm not sure if we need to build directly on top of `git2::Tree`

Can you elaborate on why? Curious to know why :)

> I like the idea of having object_id (type Oid) as part of [DirectoryContents](https://github.com/radicle-dev/radicle-git/blob/55668e6e0f07abfb3a2bdc9ac8699a656d455ffd/radicle-surf/src/file_system/directory.rs#L113) type (its name can be refactored too maybe).

I need you to expand on this. Are you saying that the `Oid` would be in place of the `File` or `Directory` itself? So something like
```rust
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Directory {
    name: Label,
    contents: BTreeMap<Label, DirectoryContents>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DirectoryContents {
    /// The `File` variant contains the file's name and the [`File`] itself.
    File {
        /// The name of the file.
        name: Label,
        /// The file data.
        id: Oid,
    },
    /// The `Directory` variant contains a sub-directory to the current one.
    Directory { id: Oid, directory: Directory },
}
```

How would the traversal work?

**Comment by keepsimple1** [comment]
> Can you elaborate on why? Curious to know why :)

I meant that we can implement `get_name` and `get_path` with `Directory` too, without on top of `git2::Tree`. 

> I need you to expand on this. Are you saying that the `Oid` would be in place of the `File` or `Directory` itself? So something like

Yes, that's what I meant. I.e. stored in `DirectoryContents::File` and `DirectoryContents::Directory`.
 
> How would the traversal work?

We can call [`contents()`](https://github.com/radicle-dev/radicle-git/blob/55668e6e0f07abfb3a2bdc9ac8699a656d455ffd/radicle-surf/src/file_system/directory.rs#L173) to iterator a `Directory` and go into the next level when an entry itself is `Directory`.

**Comment by keepsimple1** [comment]
I'll try out some of these ideas.

**Comment by FintanH** [comment]
> > Can you elaborate on why? Curious to know why :)
> 
> I meant that we can implement `get_name` and `get_path` with `Directory` too, without being on top of `git2::Tree`.

So I meant that `get_name` and `get_path` give us easy ways of accessing the trees. It's not that I care that these methods don't exist on `Directory` :) It's more the question of, "Is it worth using `Tree` to avoid having to write these kinds of functions ourselves?" Another way of thinking about it is, "Why are we defining our own `Directory` and what is it buying us?" :)


> > I need you to expand on this. Are you saying that the `Oid` would be in place of the `File` or `Directory` itself? So something like
> 
> Yes, that's what I meant. I.e. stored in `DirectoryContents::File` and `DirectoryContents::Directory`.

In place of their metadata? 

> I'll try out some of these ideas.

Ya, I'd like to see this because I'm not quite seeing what you mean without a sketch of some kind :grin:
