### ISSUE TITLE
radicle-surf: consolidate `Commit` types 

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-git#52]
Currently, we have 3 types of `Commit`s that are being worked with in `radicle-surf`:
* `git2::Commit`
* [`radicle_surf::git::Commit`](https://github.com/radicle-dev/radicle-git/blob/35b9598a29cb73c274d05f28a8c153f53a182e02/radicle-surf/src/vcs/git/commit.rs#L95-L110)
* [`radicle_surf::Commit`](https://github.com/radicle-dev/radicle-git/blob/35b9598a29cb73c274d05f28a8c153f53a182e02/radicle-surf/src/commit.rs#L50-L59)

I think this can result in confusing semantics within some of the code. For example, I noticed in a few places that we may have a `git::Commit` just to go fetch a `git2::Commit`.

I think we should:
a) Try to consolidate the two surf-defined `Commit`s into a single type if possible
b) Audit the code for this kind of extra trips to the repository and clean them up

**Comment by keepsimple1** [comment]
I've created a PR to consolidate `object::Commit` and `Commit`.  The `git2::Commit` is already hidden from the public API (if leaked, would be a bug).
