### ISSUE TITLE
`qualified!` macro requires `Qualified` in scope

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-git#54]
It seems like you can't invoke the `qualified!` macro without manually importing `Qualified`. I think it's because in the macro, we don't use a fully-qualified path: https://github.com/radicle-dev/radicle-git/blob/4f6284caf589fd7bda312fa1452a0976d5adb8a2/git-ref-format/macro/src/lib.rs#L62

I suspect `component!` may have the same issue looking at the code.

**Comment by FintanH** [comment]
The culprit is actually not importing `Qualified` here:

https://github.com/radicle-dev/radicle-git/blob/main/git-ref-format/macro/src/lib.rs#L69
