### ISSUE TITLE
surf: test structure compliance

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-git#6]
The test structure should be that all tests are gathered under a `t` sub-crate, followed by the `test` crate depending on this new crate.

- [x] Create `radicle-surf/t` crate
- [x] Add dependency to `test`
- [x] Organise surf tests under the new crate
- [x] Disable testing in `radicle-surf/Cargo.toml`
- [x] Optional: figure out if we should keep the doc tests as-is or what's the best thing to do with them. Perhaps adding `no_run` and keeping them as useful examples

**Comment by keepsimple1** [comment]
done
