### ISSUE TITLE
radicle-surf: test source modules

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-git#60]
The following modules don't have any test coverage for them:
- [x] `commit` [here](https://github.com/radicle-dev/radicle-git/blob/main/radicle-surf/t/src/commit.rs)
- [x] `object::blob` [here](https://github.com/radicle-dev/radicle-git/blob/main/radicle-surf/t/src/source.rs)
- [x] `object::tree` [here](https://github.com/radicle-dev/radicle-git/blob/main/radicle-surf/t/src/source.rs)
- [x] `revision` [here](https://github.com/radicle-dev/radicle-git/blob/main/radicle-surf/t/src/rev.rs) and [here](https://github.com/radicle-dev/radicle-git/blob/main/radicle-surf/t/src/reference.rs)

**Comment by keepsimple1** [comment]
This is done.
