### ISSUE TITLE
radicle-surf: allow doctest

### ISSUE THREAD

**Issue by keepsimple1** [radicle-dev/radicle-git#76]
https://github.com/radicle-dev/radicle-git/blob/858f13f8716450761fab6131eb22cae62829f00f/radicle-surf/Cargo.toml#L20

Instead of completely disable doctest, I think we should allow them and delete all the doctests we didn't want to keep.  Hence we will be able to add examples as doctest if deemed helpful, and take advantage of doctest to make sure examples run.

**Comment by FintanH** [comment]
Sorry, but I don't think we should. Doc tests are slow as mentioned [here](https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html#Assorted-Tricks). I think we want examples, I'd rather we add them to the `examples` directory and allow them to be run via `cargo run --example`. They will be compiler-checked by our CI scripts and we can add a script to run them manually, but I don't think it's worth running them in CI.

I'm fine with having small `no_run` examples in the doc string too, but they would have to be manually kept up-to-date.
